site_name: Gabriel Lugo
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.tracking
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.tabs.link
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: white
      accent: teal 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: white
      accent: teal
extra:
  social:
    - icon: fontawesome/brands/facebook
      link: https://lugobust.github.io/mc-labs/
    - icon: fontawesome/brands/x-twitter
      link: https://lugobust.github.io/mc-labs/
    - icon: fontawesome/brands/linkedin
      link: https://lugobust.github.io/mc-labs/
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.mark
  - abbr
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2024 <a href="https://lugobust.github.io/mc-labs/"  target="_blank" rel="noopener">Gabriel Lugo</a>